package exceptions

class ArrayIndexOutOfBoundsFoo {

    static fn test(index: int) {
        throw ArrayIndexOutOfBoundsException(index)
    }

}

